---
- name: Deploy Calculator App using Docker CLI
  hosts: local
  connection: local
  gather_facts: no

  tasks:
    - name: Remove old calculator container if exists
      ansible.builtin.command:
        _raw_params: docker rm -f calculator || true

    - name: Pull latest Docker image from DockerHub
      ansible.builtin.command:
        _raw_params: docker pull bijeet1221/scientific-calculator:latest

    - name: Run calculator container
      ansible.builtin.command:
        _raw_params: docker run -d --name calculator -it bijeet1221/scientific-calculator:latest
